services:

  # Minecraft:
  #   container_name: Minecraft
  #   hostname: minecraft
  #   image: itzg/minecraft-server
  #   restart: unless-stopped
  #   networks:
  #      games:
  #   volumes:
  #     - ${DOCKERDIR}/minecraft:/data
  #   environment:
  #     - TZ=${TZ}
  #     - EULA=TRUE
  #     - SERVER_NAME="Nico's Minecraft World"
  #     - OPS=${MINECRAFT_OPS}
  #     - MAX_PLAYERS=10
  #     - ALLOW_NETHER=true
  #     - MAX_BUILD_HEIGHT=1024
  #     - MOTD="Welcome to Nico's Minecraft World"
  #     - TYPE=PAPER
  #     #- VERSION=1.16.4
  #   labels:
  #   # Traefik - General
  #   - traefik.enable=false


  # Minecraft-Bedrock-Nico:
  #   container_name: Minecraft-Bedrock-Nico
  #   hostname: minecraft-bedrock-nico
  #   image: lomot/minecraft-bedrock
  #   restart: unless-stopped
  #   networks:
  #     games:
  #   volumes:
  #     - ${DOCKERDIR}/minecraft-bedrock/nico:/data
  #   environment:
  #     - TZ=${TZ}
  #   labels:
  #   # Traefik - General
  #   - traefik.enable=false

  # Minecraft-Bedrock-Hazel:
  #   container_name: Minecraft-Bedrock-Hazel
  #   hostname: minecraft-bedrock-hazel
  #   image: lomot/minecraft-bedrock
  #   restart: unless-stopped
  #   networks:
  #     games:
  #   volumes:
  #     - ${DOCKERDIR}/minecraft-bedrock/hazel:/data
  #   environment:
  #     - TZ=${TZ}
  #   labels:
  #   # Traefik - General
  #   - traefik.enable=false


  amp:
    container_name: amp
    hostname: amp
    image: mitchtalmadge/amp-dockerized:latest
    restart: always
    networks:
      games:
        ipv4_address: 172.22.0.1
        mac_address: 02:42:AC:C1:3B:68 # Please see the README about this field.
    volumes:
      - ${DOCKERDIR}/amp:/home/amp/.ampdata
    environment:
      - TZ=Pacific/Auckland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - Licence=${AMP_LICENSE}
      - MODULE=ADS
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.amp.loadbalancer.server.port=8080
    # Traefik - Router - HTTPS
    - traefik.http.routers.amp.rule=Host(`amp.${DOMAIN}`)
    - traefik.http.routers.amp.entryPoints=websecure
    - traefik.http.routers.amp.middlewares=Real-IP@file, Headers@file

  playit:
    container_name: playit
    hostname: playit
    image: ghcr.io/playit-cloud/playit-agent:0.16
    restart: always
    networks: 
      games:
        ipv4_address: 172.22.0.253
    environment:
      - SECRET_KEY=${PLAYIT_SECRET}

#Shared Networks between containers    
networks:
  games:
    name: games
    ipam:
      driver: default
      config:
        - subnet: "10.1.20.0/24"

  #External VLANs
  Internal:
    name: O.and.A
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.254