services: 

  SnapRAID: 
    container_name: SnapRAID 
    hostname: SnapRAID 
    privileged: true
    image: xagaba/snapraid
    restart: always
    networks:
       storage:
    volumes:
      - ${DOCKERDIR}/snapraid:/config
      - /mnt/array:/mnt/array
      - /dev/disk:/dev/disk
    devices:  
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    labels:
    # Traefik - Service
    - traefik.enable=false

  Scrutiny:
    container_name: Scrutiny
    hostname: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: always
    networks:
      storage:
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    volumes:
      - ${DOCKERDIR}/scrutiny/config:/opt/scrutiny/config
      - ${DOCKERDIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    devices:  
      - /dev/nvme0:/dev/nvme0
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    # Traefik - Router - HTTPS
    - traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN}`)
    - traefik.http.routers.scrutiny.entryPoints=websecure
    - traefik.http.routers.scrutiny.middlewares=Real-IP@file, Headers@file

  Crashplan:
    container_name: crashplan
    hostname: crashplan
    image: jlesage/crashplan-pro
    restart: always
    networks:
      storage:
    volumes:
      - ${DOCKERDIR}/crashplan/config:/config
      - /mnt/storage:/storage:ro
    environment:
      - CRASHPLAN_SRV_MAX_MEM=4096
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.crashplan.loadbalancer.server.port=5800
    # Traefik - Router - HTTPS
    - traefik.http.routers.crashplan.rule=Host(`crashplan.${DOMAIN}`)
    - traefik.http.routers.crashplan.entryPoints=websecure
    - traefik.http.routers.crashplan.middlewares=Real-IP@file, Headers@file

#Shared Networks between containers
networks:
  #Internal Docker Networks
  storage:
    name: storage