services: 

  SnapRAID: 
    container_name: SnapRAID 
    hostname: SnapRAID 
    privileged: true
    image: xagaba/snapraid
    restart: always
    networks:
       storage:
    volumes:
      - ${DOCKERDIR}/snapraid:/config
      - /mnt/array:/mnt/array
      - /dev/disk:/dev/disk
    devices:  
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    labels:
    # Traefik - Service
    - traefik.enable=false

  Scrutiny:
    container_name: Scrutiny
    hostname: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: always
    networks:
      storage:
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    volumes:
      - ${DOCKERDIR}/scrutiny/config:/opt/scrutiny/config
      - ${DOCKERDIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    devices:  
      - /dev/nvme0:/dev/nvme0
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    # Traefik - Router - HTTPS
    - traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN}`)
    - traefik.http.routers.scrutiny.entryPoints=websecure
    - traefik.http.routers.scrutiny.middlewares=Real-IP@file, Headers@file
    # AutoKuma - Uptime Kuma Monitor
    - kuma.scrutiny.http.name=Scrutiny
    - kuma.scrutiny.http.url=https://scrutiny.${DOMAIN}
    - kuma.scrutiny.http.headers=${KUMA_CFHEADERS}
    - kuma.scrutiny.http.parent_name=storage

  Crashplan:
    container_name: crashplan
    hostname: crashplan
    image: jlesage/crashplan-pro
    restart: always
    networks:
      storage:
    volumes:
      - ${DOCKERDIR}/crashplan/config:/config
      - /mnt/storage:/storage:ro
    environment:
      - CRASHPLAN_SRV_MAX_MEM=4G
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.crashplan.loadbalancer.server.port=5800
    # Traefik - Router - HTTPS
    - traefik.http.routers.crashplan.rule=Host(`crashplan.${DOMAIN}`)
    - traefik.http.routers.crashplan.entryPoints=websecure
    - traefik.http.routers.crashplan.middlewares=Real-IP@file, Headers@file
    # AutoKuma - Uptime Kuma Monitor
    - kuma.crashplan.http.name=CrashPlan
    - kuma.crashplan.http.url=https://crashplan.${DOMAIN}
    - kuma.crashplan.http.headers=${KUMA_CFHEADERS}
    - kuma.crashplan.http.parent_name=storage


  PBS:
    container_name: pbs
    hostname: pbs
    image: ayufan/proxmox-backup-server:latest
    restart: always
    networks:
    networks:
      IoT:
        ipv4_address: 10.1.11.210
    volumes:
      - ${DOCKERDIR}/pbs/etc:/etc/proxmox-backup
      - ${DOCKERDIR}/pbs/var/log:/var/log/proxmox-backup
      - ${DOCKERDIR}/pbs/var/lib:/var/lib/proxmox-backup
      - /mnt/storage/backups/pve:/backups
    tmpfs:
      - /run
    cap_add:
      - SYS_RAWIO # smartctl support
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.pbs.loadbalancer.server.port=8007
    # Traefik - Router - HTTPS
    - traefik.http.routers.pbs.rule=Host(`pbs.${DOMAIN}`)
    - traefik.http.routers.pbs.entryPoints=websecure
    - traefik.http.routers.pbs.middlewares=Real-IP@file, Headers@file
    # AutoKuma - Uptime Kuma Monitor
    - kuma.pbs.http.name=pbs
    - kuma.pbs.http.url=https://crashplan.${DOMAIN}
    - kuma.pbs.http.headers=${KUMA_CFHEADERS}
    - kuma.pbs.http.parent_name=storage

    
#Shared Networks between containers
networks:
  #Internal Docker Networks
  storage:
    name: storage
  #External VLANs
  IoT:
    name: O.and.A (IoT)
    driver: macvlan
    driver_opts:
      parent: eno1.10
    ipam:
      config:
        - subnet: 10.1.10.0/23
          gateway: 10.1.10.254