services: 

  Autogen-Studio:
    container_name: autogen
    hostname: autogen
    image: ghcr.io/lludlow/autogen-studio
    restart: always
    networks:
      ai:
    environment:
      - AUTOGEN_HOST=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    labels:
    # Traefik - Service
    - traefik.enable=true
    - traefik.http.services.autogen.loadbalancer.server.port=8081
    # Traefik - Router - HTTPS
    - traefik.http.routers.autogen.rule=Host(`autogen.${DOMAIN}`)
    - traefik.http.routers.autogen.entryPoints=websecure
    - traefik.http.routers.autogen.middlewares=Real-IP@file, Headers@file

  Ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama
    restart: always
    networks:
      ai:
    labels:
    # Traefik - Service
    - traefik.enable=false

#Shared Networks between containers
networks:
  #Internal Docker Networks
  ai:
    name: ai
    
